### ISSUE TITLE
Target Binnary Version in false

### ISSUE THREAD

**Issue by cris7hian30-df** [sweatco/react-native-code-push-diff#1]
When using the code-push-diff library to upload a bundle to CodePush, the -t argument (target-binary-version) is not being handled correctly. The command passes the -t option as false during execution, leading to an invalid binary version error.

Input:
`yarn code-push-diff release-react -a <myApp> -d Development -t "3.20.0" --base "<baseBranch>`

Output:
`appcenter codepush release -a <myApp> -d Development -t false`
Error: Invalid binary version(s) for a release.

**Comment by Augustach** [comment]
Hey, thanks for your report. It should be fixed in [1.1.6](https://github.com/sweatco/react-native-code-push-diff/releases/tag/v1.1.6).

Tested it in the example app using the following command:

`yarn code-push-diff release-react -a <app> -d Staging -t "1.0" --base main --npm yarn`

**Comment by cris7hian30-df** [comment]
> Hey, thanks for your report. It should be fixed in [1.1.6](https://github.com/sweatco/react-native-code-push-diff/releases/tag/v1.1.6).
> 
> Tested it in the example app using the following command:
> 
> `yarn code-push-diff release-react -a <app> -d Staging -t "1.0" --base main --npm yarn`

I installed the version but now it defaults to the one in the package, and in ios the problem continues and the -t returns false and the command fails.

**Comment by Augustach** [comment]
You are right. There was still an issue with the custom target version.

Could you please try the [1.2.1](https://github.com/sweatco/react-native-code-push-diff/releases/tag/v1.2.1) release?

**Comment by cris7hian30-df** [comment]
Thanks, the bug is fixed but now when I send a push code it doesn't affect the package, it doesn't send the changes, it seems that it only updates but it doesn't do any update.

**Comment by Augustach** [comment]
I just checked the example in the library, and I can see the new bundle on App Center. ( I used ` yarn code-push-diff release-react -a <app>  -d Staging -t "5.0" --base main --npm yarn `)

Could you please try the command `yarn code-push-diff bundle <myApp> -d Development -t "3.20.0" --base <baseBranch>`? You can also add a specific folder for the output using `--output-dir ./<path_to_your_folder>`.

I suspect it might also be because there is an identical bundle on App Center (see this [link](https://learn.microsoft.com/en-us/appcenter/distribution/codepush/cli#no-duplicate-release-error-parameter)).

**Comment by cris7hian30-df** [comment]
This works but my app crashes when installing the update in iOS, on Android this does not happen.

**Comment by Augustach** [comment]
Hey @cris7hian30-df

I see that you closed the issue. Have you handled the iOS side, or is there still an issue?

**Comment by cris7hian30-df** [comment]
I opened a new issue because the problem is different from the initial issue. #8
